_merge: deep

# Image
image:
  retina:
    desktop: true

# Javascript
carousel: false
bootstrap:
  modal: false
map: false

# Brand
brand:
  name: Medicalify
  email: medicalify@uncinq.dev
  url: medicalify.io
  your:
    of: de votre cabinet
    to: Ã  votre cabinet